### PR TITLE
Release 1.0.3

### PR DESCRIPTION
**Pull request by mcmlxxxviii**
1. Embeds latest integration code (version 5)
2. No more '_weq' global and 'widgetVersion' option
3. Integration does not assumesPageview() simply to capture any
   initial page name, data
4. Integration is readyOnInitialize()
5. WebEngage 2.0 features data collection capablities - event
   tracking, identifying users with their attributes etc.

### CODE REVIEW

**Comment by f2prateek** [comment]
Can you send these as separate PRs so it's easier to review the changes?

**Comment by mcmlxxxviii** [comment]
Yes though I can only logically break into two - one PR for changes 1 to 4 (all are related to the integration snippet) and another for 5.

Sound good?

**Comment by f2prateek** [comment]
I see, I think it's fine for now, we'll review this PR as is.

**Comment by mcmlxxxviii** [comment]
@f2prateek, is the review complete?

**Comment by hankim813** [comment]
@segment-integrations/core ping

**Comment by mcmlxxxviii** [comment]
@f2prateek @segment-integrations/core this PR has been open for some time now. Can you please review?

A couple of our (WebEngage) customers use this Segment integration to enable WebEngage's engagement products on their websites and they have been inquiring for event tracking and user identification support with Segment.

Thanks

cc @WebEngage/team

**Comment by mcmlxxxviii** [comment]
@f2prateek PR has been open since late Feb. Can you please review?

As stated already, our customers need WebEngage's latest features available in this Segment integration.

**Comment by f2prateek** [comment]
Sorry but it needs to rebased against the changes on master https://github.com/segment-integrations/analytics.js-integration-webengage/commits/master

**Comment by jgershen** [comment]
@f2prateek it was a straightforward rebase and passed tests, so I just did the update for them given how long we'd taken here. (Then I accidentally merged it from CLI instead of rebasing the pull request -- oops.)

**Comment by jgershen** [comment]
as a result although it says "passed tests" here it really hasn't passed the new cross-browser tests in CI yet. I'll keep an eye on this as it builds in master and revert or fix if necessary.

**Comment by jgershen** [comment]
Some minor test breakages but I think they are all related to browser timeouts; I'm on it from here. @mcmlxxxviii I will update when we release the new version. Thanks for bearing with us here.

**Comment by f2prateek** [comment]
Thanks!

**Comment by jgershen** [comment]
Okay, I was premature in merging that; tests were not passing in Internet Explorer. 

@mcmlxxxviii: I'm specifically seeing an error around calling `remove` in IE.
screenshot 2016-07-12 14 38 15

Can you rebase your code atop the current `master` of this repository (as @f2prateek suggested), fix the IE incompatibility, and then send a new pull request? That way the new tests should correctly screen for this issue.

Thanks!

**Comment by mcmlxxxviii** [comment]
Yes! we will send a fresh PR the week after the next.

**Pull request merged**
